#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable postfix.service

  if test -f "disabled.bin"; then
    echo "smtp is already disabled."
  else
    touch "disabled.bin"
    if systemctl is-active --quiet postfix-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop postfix.service
    else
      echo "smtp will be disabled on next reboot."
    fi
  fi

fi

