#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable postfix.service

  if test ! -f "disabled.bin"; then
    echo "smtp is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet postfix-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart postfix-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart postfix.service
    else
      echo "smtp will be enabled on next reboot."
    fi
  fi

fi

