#!/bin/sh

set -e
umask 0002

OPTIONS="--polar disabled --hostname hostname --bytes message-size-limit --fqdn relayhost"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if test -f "disabled.bin"; then
    if systemctl is-active --quiet postfix-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop postfix.service
    else
      echo "smtp will be disabled on next reboot."
    fi
  else
    if systemctl is-active --quiet postfix-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart postfix-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart postfix.service
    else
      echo "smtp will be enabled on next reboot."
    fi
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

