#!/bin/sh

set -e
umask 0002

OPTIONS="--hostname hostname --bytes message-size-limit --fqdn relayhost"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postfix-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postfix.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

