#!/bin/bash

#
# Postfix Autodiscovery - Limits
# ==============================
# 
# This script autogenerates the limits configuration for a postfix server.

set -e
umask 0022



#
# main.cf - Limits
# ----------------

if [ -s "/etc/device/services/mail/smtp/message-size-limit.txt" ]; then

  message_size_limit="$(head -n 1 /etc/device/services/mail/smtp/message-size-limit.txt)"

  cat >> "main.cf" <<- EOF
# Note: message size limit from /etc/device/services/mail/smtp/message-size-limit.txt
# Modify as follows: device services mail smtp set message-size-limit=${message_size_limit}
message_size_limit = ${message_size_limit}
EOF

  mailbox_size_limit="$(postconf -dh mailbox_size_limit)"

  if test "${message_size_limit}" -gt "${mailbox_size_limit}"; then

    # mailbox_size_limit at least message_size_limit
    cat >> "main.cf" <<- EOF
mailbox_size_limit = ${message_size_limit}
EOF

  fi

fi


