#!/bin/bash

#
# Postfix Autodiscovery - Milters
# ===============================
# 
# This script autogenerates the milters configuration for a postfix server.

set -e
umask 0022



#
# main.cf - MILTER
# ----------------

if [ -d "/run/milters" ]; then

  for milter in $(find "/run/milters" | sort)
  do
    if [ -h "${milter}" ]; then
      milter_socket=$(realpath -m "${milter}")
      milter_path=$(dirname "${milter_socket}")
      milter_group=$(stat -c %G "${milter_path}")
      usermod -a -G "${milter_group}" postfix
      smtpd_milters+=" unix:"
      smtpd_milters+="${milter_socket}"
    elif [ -f "${milter}" ]; then
      smtpd_milters+=" inet:"
      smtpd_milters+=$(cat "${milter}")
    fi
  done

  cat >> "main.cf" <<- EOF
# MILTERS
#
# Configured based on contents of /run/milters
#
smtpd_milters =${smtpd_milters}

EOF

fi


