#!/bin/bash

#
# Postfix Autodiscovery - TLS
# ===========================
# 
# This script autogenerates the inbound TLS configuration for a postfix server.

set -e
umask 0022


#
# Generate Config
# ---------------
#

install -m 0750 -d /run/postfix-tls /run/postfix-tls/ca-certs /run/postfix-tls/certs /run/postfix-tls/private

if [ -f "/etc/device/services/mail/tls/tls-dns.txt" ]; then

  tls_dns=$(head -n 1 /etc/device/services/mail/tls/tls-dns.txt)

  logger -t postfix-autodiscovery "importing postfix server certificate/key..."

  redwax-tool --pem-in="/etc/pki/tls/private/*" \
              --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
              --pem-in="/etc/pki/tls/certs/*.pem" \
              --filter=verify \
              --filter-hostname="${tls_dns}" \
              --filter-current \
              --cert-out --chain-out --no-key-out \
              --pem-out="/run/postfix-tls/certs/smtpd.crt" \
              --no-cert-out --no-chain-out --trust-out \
              --pem-out="/run/postfix-tls/ca-certs/ssl-cacert.pem" \
              --no-chain-out --no-trust-out --key-out \
              --pem-out="/run/postfix-tls/private/smtpd.key" || echo "Could not import cert/key for tls" > "error"

  if test ! -f "error"; then
    logger -t postfix-autodiscovery "imported postfix server certificate/key."
  else
    logger -t postfix-autodiscovery "failed to import postfix server certificate/key."
  fi

  smtpd_tls_cert_file="/run/postfix-tls/certs/smtpd.crt"
  smtpd_tls_key_file="/run/postfix-tls/private/smtpd.key"
  smtpd_tls_security_level="may"

  cat >> "main.cf" <<- EOF
# Note: certificate from /etc/device/services/mail/tls/tls-dns.txt

# INBOUND TLS CONFIGURATION
#
# The following certificates are used for inbound connections.

# The full pathname of a file with the Postfix SMTP server RSA certificate
# in PEM format. Intermediate certificates should be included in general,
# the server certificate first, then the issuing CA(s) (bottom-up order).
#
smtpd_tls_cert_file = ${smtpd_tls_cert_file}

# The full pathname of a file with the Postfix SMTP server RSA private key
# in PEM format. The private key must be accessible without a pass-phrase,
# i.e. it must not be encrypted.
#
smtpd_tls_key_file = ${smtpd_tls_key_file}

# Announce STARTTLS support to remote SMTP clients, but do not require that
# clients use TLS encryption (opportunistic TLS inbound).
#
smtpd_tls_security_level = ${smtpd_tls_security_level}

EOF


  #
  # Open up inet_interfaces
  postconf -c . inet_interfaces=all

fi


if test -L "/etc/device/services/mail/tls/tls-ca-certs.crt"; then
  smtp_tls_CAfile=$(readlink -f "/etc/device/services/mail/tls/tls-ca-certs.crt")
else
  smtp_tls_CAfile=/etc/pki/tls/certs/ca-bundle.crt
fi

smtp_tls_security_level="may"

cat >> "main.cf" <<- EOF

# Note: CA certificate from /etc/device/services/mail/tls/tls-client-dns.txt.

# OUTBOUND TLS CONFIGURATION
#
# The following certificates are used for outbound connections.

# Directory with PEM format Certification Authority certificates that the
# Postfix SMTP client uses to verify a remote SMTP server certificate.
#
smtp_tls_CApath = /etc/pki/tls/certs

# The full pathname of a file containing CA certificates of root CAs
# trusted to sign either remote SMTP server certificates or intermediate CA
# certificates.
#
smtp_tls_CAfile = ${smtp_tls_CAfile}

# Use TLS if this is supported by the remote SMTP server, otherwise use
# plaintext (opportunistic TLS outbound).
#
smtp_tls_security_level = ${smtp_tls_security_level}

EOF

if [ -f "/etc/device/services/mail/tls/tls-client-dns.txt" ]; then

  tls_client_dns=$(head -n 1 /etc/device/services/mail/tls/tls-client-dns.txt)

  logger -t postfix-autodiscovery "importing postfix client certificate/key..."

  install -m 0750 -d /run/postfix-tls /run/postfix-tls/ca-certs /run/postfix-tls/certs /run/postfix-tls/private

  redwax-tool --pem-in="/etc/pki/tls/private/*" \
              --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
              --pem-in="/etc/pki/tls/certs/*.pem" \
              --filter=verify \
              --filter-hostname="${tls_client_dns}" \
              --filter-current \
              --cert-out --chain-out --no-key-out \
              --pem-out="/run/postfix-tls/certs/smtp.crt" \
              --no-cert-out --no-chain-out --trust-out \
              --pem-out="/run/postfix-tls/ca-certs/ssl-cacert.pem" \
              --no-chain-out --no-trust-out --key-out \
              --pem-out="/run/postfix-tls/private/smtp.key" || echo "Could not import cert/key for tls-client" > "error"

  if test ! -f "error"; then
    logger -t postfix-autodiscovery "imported postfix client certificate/key."
  else
    logger -t postfix-autodiscovery "failed to import postfix client certificate/key."
  fi

  smtp_tls_cert_file="/run/postfix-tls/certs/smtp.crt"
  smtp_tls_key_file="/run/postfix-tls/private/smtp.key"

  cat >> "main.cf" <<- EOF

# Note: client certificates from /etc/device/services/mail/tls/tls-client-dns.txt.

smtp_tls_cert_file = ${smtp_tls_cert_file}
smtp_tls_key_file = ${smtp_tls_key_file}

EOF

fi

