#!/bin/bash

#
# Postfix Autodiscovery - TLS
# ===========================
# 
# This script autogenerates the inbound TLS configuration for a postfix server.

set -e
umask 0022


#
# Generate Config
# ---------------
#

install -m 0750 -d /run/postfix/ca-certs /run/postfix/certs /run/postfix/private

if [ -f "/etc/device/services/mail/tls/tls-dns.txt" ]; then

  tls_dns=$(head -n 1 /etc/device/services/mail/tls/tls-dns.txt)

  logger -t postfix-autodiscovery "importing postfix server certificate/key..."

  redwax-tool --pem-in="/etc/pki/tls/private/*" \
              --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
              --pem-in="/etc/pki/tls/certs/*.pem" \
              --filter=search \
              --filter-hostname="${tls_dns}" \
              --filter-current \
              --parameter-out --order-out=key-first \
              --cert-out --chain-out --key-out \
              --pem-out="/run/postfix/private/smtpd.crt" \
              --order-out=all \
              --no-cert-out --no-chain-out --no-key-out --trust-out \
              --pem-out="/run/postfix/ca-certs/ssl-cacert.pem" || echo "Could not import cert/key for tls" > "error"

  if test ! -f "error"; then
    logger -t postfix-autodiscovery "imported postfix server certificate/key."
  else
    logger -t postfix-autodiscovery "failed to import postfix server certificate/key."
  fi

if test -L "/etc/device/services/mail/tls/tls-client-ca.crt"; then
  smtpd_tls_CAfile=$(readlink -f "/etc/device/services/mail/tls/tls-client-ca.crt")
else
  smtpd_tls_CAfile=
fi

  smtpd_tls_chain_files="/run/postfix/private/smtpd.crt"

  smtpd_tls_security_level="may"

  cat >> "main.cf" <<- EOF
# Note: certificate from /etc/device/services/mail/tls/tls-dns.txt

# INBOUND TLS CONFIGURATION
#
# The following certificates are used for inbound connections.

# List of one or more PEM files, each holding one or more private keys
# directly followed by a corresponding certificate chain. The file names
# are separated by commas and/or whitespace.
#
# Each key must appear immediately before the corresponding certificate,
# optionally followed by additional issuer certificates that complete the
# certificate chain for that key. When multiple files are specified, they
# are equivalent to a single file that is concatenated from those files
# in the given order. Thus, while a key must always precede its certificate
# and issuer chain, it can be in a separate file, so long as that file is
# listed immediately before the file that holds the corresponding
# certificate chain. Once all the files are concatenated, the sequence of
# PEM objects must be: key1, cert1, [chain1], key2, cert2, [chain2], ...,
# keyN, certN, [chainN].
#
smtpd_tls_chain_files = ${smtpd_tls_chain_files}

# A file containing (PEM format) CA certificates of root CAs trusted to
# sign either remote SMTP client certificates or intermediate CA
# certificates.
#
smtpd_tls_CAfile = ${smtpd_tls_CAfile}

# Announce STARTTLS support to remote SMTP clients, but do not require that
# clients use TLS encryption (opportunistic TLS inbound).
#
smtpd_tls_security_level = ${smtpd_tls_security_level}

# When TLS encryption is optional in the Postfix SMTP server, do not
# announce or accept SASL authentication over unencrypted connections.
#
smtpd_tls_auth_only = yes

# Ask a remote SMTP client for a client certificate. This information is
# needed for certificate based mail relaying with, for example, the
# permit_tls_clientcerts feature.
#
smtpd_tls_ask_ccert = yes

# Request that the Postfix SMTP server produces Received: message headers that
# include information about the protocol and cipher used, as well as the
# remote SMTP client CommonName and client certificate issuer CommonName. This
# is disabled by default, as the information may be modified in transit
# through other mail servers. Only information that was recorded by the final
# destination can be trusted.
#
smtpd_tls_received_header = yes

EOF


  #
  # Open up inet_interfaces
  postconf -c . inet_interfaces=all

fi


if test -L "/etc/device/services/mail/tls/tls-ca.crt"; then
  smtp_tls_CAfile=$(readlink -f "/etc/device/services/mail/tls/tls-ca.crt")
else
  smtp_tls_CAfile=/etc/pki/tls/certs/ca-bundle.crt
fi

smtp_tls_security_level="may"

cat >> "main.cf" <<- EOF

# Note: CA certificate from /etc/device/services/mail/tls/tls-client-dns.txt.

# OUTBOUND TLS CONFIGURATION
#
# The following certificates are used for outbound connections.

# Directory with PEM format Certification Authority certificates that the
# Postfix SMTP client uses to verify a remote SMTP server certificate.
#
smtp_tls_CApath =

# The full pathname of a file containing CA certificates of root CAs
# trusted to sign either remote SMTP server certificates or intermediate CA
# certificates.
#
smtp_tls_CAfile = ${smtp_tls_CAfile}

# Use TLS if this is supported by the remote SMTP server, otherwise use
# plaintext (opportunistic TLS outbound).
#
smtp_tls_security_level = ${smtp_tls_security_level}

EOF

if [ -f "/etc/device/services/mail/tls/tls-client-dns.txt" ]; then

  tls_client_dns=$(head -n 1 /etc/device/services/mail/tls/tls-client-dns.txt)

  logger -t postfix-autodiscovery "importing postfix client certificate/key..."

  install -m 0750 -d /run/postfix/ca-certs /run/postfix/certs /run/postfix/private

  redwax-tool --pem-in="/etc/pki/tls/private/*" \
              --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
              --pem-in="/etc/pki/tls/certs/*.pem" \
              --filter=search \
              --filter-hostname="${tls_client_dns}" \
              --filter-current \
              --parameter-out --order-out=key-first \
              --cert-out --chain-out --key-out \
              --pem-out="/run/postfix/private/smtp.crt" \
              --order-out=all \
              --no-cert-out --no-chain-out --no-key-out --trust-out \
              --pem-out="/run/postfix/ca-certs/ssl-cacert.pem" || echo "Could not import cert/key for tls-client" > "error"

  if test ! -f "error"; then
    logger -t postfix-autodiscovery "imported postfix client certificate/key."
  else
    logger -t postfix-autodiscovery "failed to import postfix client certificate/key."
  fi

  smtp_tls_chain_files="/run/postfix/private/smtp.crt"

  cat >> "main.cf" <<- EOF

# Note: client certificates from /etc/device/services/mail/tls/tls-client-dns.txt.

# List of one or more PEM files, each holding one or more private keys
# directly followed by a corresponding certificate chain. The file names
# are separated by commas and/or whitespace.
#
# Each key must appear immediately before the corresponding certificate,
# optionally followed by additional issuer certificates that complete the
# certificate chain for that key. When multiple files are specified, they
# are equivalent to a single file that is concatenated from those files
# in the given order. Thus, while a key must always precede its certificate
# and issuer chain, it can be in a separate file, so long as that file is
# listed immediately before the file that holds the corresponding
# certificate chain. Once all the files are concatenated, the sequence of
# PEM objects must be: key1, cert1, [chain1], key2, cert2, [chain2], ...,
# keyN, certN, [chainN].
#
smtp_tls_chain_files = ${smtp_tls_chain_files}

EOF

fi

restorecon -R /run/postfix

