#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --fqdn name"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postfix-autodiscovery.target
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postfix.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postfix-postdiscovery.target

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

